version: '2'
services:
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql # データの永続化
      - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期データ投入
    environment:
      - MYSQL_ROOT_PASSWORD="pass" #rootパスワードの設定

  apache:
      build:
        context: ./apache/
      ports:
        - "80:80"
      volumes:
        - ./apache/logs:/usr/local/apache2/logs # データの永続化
        - ./apache/html:/usr/local/apache2/htdocs # データの永続化
        - ./apache/cgi-bin:/usr/local/apache2/cgi-bin # データの永続化
      links:
        - mysql
